# You can add one username per supported platform and one custom link
patreon: shindakun
# open_collective: # Replace with your Open Collective username
ko_fi: shindakun
# custom: https://snipeitapp.com/donate